__copyright__ = 'Copyright (C) 2017 Daichi Yoshikawa'
__version__ = '0.1.0'
__license__ = 'BSD-3-Clause'
__author__ = 'Daichi Yoshikawa'
__author_email__ = 'daichi.yoshikawa@gmail.com'
__url__ = 'https://github.com/daichi-yoshikawa/dnn'
